project:
  type: website
  output-dir: docs
  resources:
    - assets/*
  
lang: en

execute:
  freeze: false
  cache: false

format:
  html:
      theme:
        light: 
          - flatly
          - scss/custom.scss
        dark:
          - darkly
          - scss/custom.scss
      css: assets/styles.css
      callout-appearance: simple
      toc: true
      toc-depth: 4
      smooth-scroll: true
      highlight-style: atom-one
      number-sections: true
      number-depth: 4
      pagetitle: "{{< var meta.title >}}"

website:
  repo-url: https://github.com/shunyakmr/ULMS744-2025
  repo-actions: [issue]
  page-navigation: true
  page-footer:
    center: "Footer. Available under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."
  search:
    location: sidebar
    type: overlay
  sidebar:
    style: floating
    collapse-level: 2
    logo: assets/ULMS744-logo.svg
    tools:
      - icon: github
        href: https://github.com/shunyakmr/ULMS744-2025
    contents:
      - section: "Module Overview"
        contents:
          text: "Welcome"
          file: 00-index.qmd
      - section: "Reproducible Workflows for Sports Analytics"
        contents:
        - 01-start.qmd
        - 02-api.qmd
        - 03-shiny1.qmd
        - 04-shiny2.qmd
        - 05-portfolio.qmd
      - section: "Additional Resources"
        contents:
        - 09-project.qmd
  
editor: visual

